repos:
-   repo: local
    hooks:
    - id: system
      name: Black
      entry: poetry run black .
      pass_filenames: false
      language: system
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint
      args: ['--rcfile=.pylintrc', --disable=redefined-builtin]
      language: system
      types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: 'mypy'
        additional_dependencies:
          - 'pydantic'
          - 'types-requests'
