repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: python -m pylint.__main__
      args: ['--rcfile=.pylintrc', --disable=redefined-builtin]
      language: system
      types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: 'mypy'
        additional_dependencies:
          - 'pydantic'
